sudo: false
language: java
jdk:
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
install: true
script: misc/travis-build/travis-build.sh $TARGET
cache:
  directories:
  - $HOME/.m2
  - $HOME/.cache/bower
matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=deploy
    - jdk: oraclejdk8
      env: TARGET=sonar
    - jdk: oraclejdk8
      env: TARGET=checker
      # firefox
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=firefox SAUCELABS_BROWSER_VERSION=
      # chrome
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=chrome SAUCELABS_BROWSER_VERSION=
      # safari
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.10" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=8
      # internet explorer
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=11
env:
  matrix:
    - TARGET=test GLOWROOT_UNSHADED=false GLOWROOT_HARNESS=javaagent
before_deploy:
  - mkdir -p s3/snapshots
  - cp distribution/target/glowroot-*-dist.zip s3/snapshots
  - cd s3
deploy:
  provider: s3
  access_key_id:
    secure: "TKm8rMaM7//dszw+GpTj+HzZ5BXdiYZmG/EpMRTIy1uKHnXvw5Lf63B1rOQjUclnwqYHSV1r890XHUPeIZddcxJK9nRaOmVg/5AUZIh/HbjqT+M91OkX4SIQiyW+HV2aF5LF+RPTVIB24NbSok3jrZnPRRVGX6VjeEIFYQRXBQY="
  secret_access_key:
    secure: "ItGgSVtNccZaA7BGRDFPmTjw2Gb6R0xLPGbF4F2W1CbUVA+qlW7MaOeQ8jZwlh5O6YelFN2dcehCXbsHnPnkfdl+bCsBJ4QqdSWiCuRYIh0gHFwNjdS7syJ3/T55nhrhSzd398R/IquSbSSk/s2UkpUoAj4NgmIqrlt8MScaslU="
  bucket: glowroot
  skip_cleanup: true
  on:
    jdk: oraclejdk8
    branch: master
    repo: glowroot/glowroot
    condition: "$TARGET = deploy"
addons:
  sauce_connect: true
